server:
  port: 9999
spring:
  application:
    name: manage-system
  profiles:
    active: '@pom.profile.name@'
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/manager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: maple
      password: maple
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: js/**,css/**,common/**
      cache: false
  liquibase:
    enabled: true
  thymeleaf:
    cache: false
  redis:
    lettuce:
      pool:
        #连接池中的最小空闲连接
        min-idle: 1
        #连接池中的最大空闲连接
        max-idle: 100
        #连接池最大阻塞等待时间
        max-wait: 1000ms
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      select-strategy: not_empty
  type-enums-package: com.maple.server.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
cache:
  prefix: custom-cache-
logging:
  path: logs/
  level:
    root: info
    org: info
    net: info
    io: info
    springfox.documentation: info
    sun: info
    com: info
mp:
  tool:
    generator:
      gen-tables: test
      model-name: test
  shiro:
    cache:
      redis:
        enabled: true
        principal-id-field-name: id
    advisor-auto-proxy-creator:
      use-prefix: true
      proxy-target-class: false
    filter-chain:
      # 放行登录页面
      - /login:anon
      # 放行token获取
      - /token:anon
      # 配置退出过滤器,具体的退出代码Shiro已经实现
      - /logout:logout
      # 放行登陆验证
      - /user/checkLogin:anon
      # 放行错误页面
      - /error/**:anon
      # 放行健康检查
      - /actuator/**:anon
      # 放行swagger文挡
      - /doc.html:anon
      - /swagger-resources/**:anon
      - /swagger-ui.html:anon
      - /v2/**:anon
      - /webjars/**:anon
      # 配置记住我或认证通过可以访问的地址
      - /user/userList:user
      - /:user
      # 配置静态资源放行
      - /css/**:anon
      - /common/**:anon
      - /js/**:anon
      - /images/*/**:anon
      - /user/login:anon
      # 其他所有url都必须认证通过才可以访问
      - /**:jwt,authc
    realms:
      - realm:
          target: com.maple.server.function.auth.MyRealm
          credentials-matcher:
            target: org.apache.shiro.authc.credential.HashedCredentialsMatcher
            property:
              hashAlgorithmName: MD5
              hashIterations: 2
              storedCredentialsHexEncoded: true
    web:
      filters:
        authc: com.maple.starter.shiro.filter.CustomUserFilter
    jwt:
      enable: true
      secret: DEB2FB335003A340D5B2BEB970184456
knife4j:
  basic:
    enable: true
    username: maple
    password: 1
shiro:
  loginUrl: /login
  successUrl: /
  sessionManager:
    cookie:
      name: MPJSESSIONID
      maxAge: 200000
  unauthorizedUrl: /error/403
debug: true